### ISSUE TITLE
Telescope Window name

### ISSUE THREAD

**Issue by pbower** [LintaoAmons/bookmarks.nvim#10]
Hi there,

Would you consider renaming the default Telescope window name to 'Bookmarks'' or similar, from 'Select from List: Default'? 

![image](https://github.com/LintaoAmons/bookmarks.nvim/assets/37089506/d75165ad-6734-41a8-809b-b7e815cbbbcc)

This will help with :
* Being able to tell this plugin apart when lots of telescope plugins are mapped to different key combinations.
* Consistency with other plugins that read for e.g., File Browser, Live Grep, etc in that field that state their purpose, as there is nothing indicating that it refers to the Bookmarks.

Thanks heaps for considering this, it would be a massive help!

**Comment by LintaoAmons** [comment]
Yeah, of course we can do it.

But I still want the hint about which list I'm choosing from, which format should be better?

`Bookmarks: [Default]`

**Comment by LintaoAmons** [comment]
The impl has been pushed, sorry for the late~
