### ISSUE TITLE
Canceling bookmark creation creates bookmark anyway

### ISSUE THREAD

**Issue by MystikReasons** [LintaoAmons/bookmarks.nvim#12]
When opening the bookmark creation dialog field ":BookmarksMark<cr>" and then quitting out of it with 'Escape', it creates an unnamed bookmark anyway. I would have assumed that it just cancels the current operation.

The command ":BookmarksGoto<cr>" also shows the created unnamed bookmark.

![image](https://github.com/LintaoAmons/bookmarks.nvim/assets/18333048/7189c7e7-0403-45dc-895f-1353f89df9ca)

I assume this is a bug?

**Comment by LintaoAmons** [comment]
Ehh, it's not a bug. 

Cause sometimes I don't bother to think...
Just want to make it

**Comment by MystikReasons** [comment]
Do you want to handle that matter or should I propse a simple solution?

**Comment by LintaoAmons** [comment]
You can simply run the command(shortcut) again to toggle it off.

**Comment by LintaoAmons** [comment]
I'm not sure if we can differentiate the user cancelled the process or just put nothing into the input box~ 
We can take a look

**Comment by MystikReasons** [comment]
You could check if the return value is `nil`
> ...or nil if the user aborted the dialog

```
 Return (multiple):
(vim.SystemObj?) Command object, or nil if not found. (string?) Error message on failure 
```

**Comment by ttytm** [comment]
What I would do is to at least set buffer keymaps when entering the dressings dialog for escape and ctrl-c so that if those are hit a bookmark is not created.
