### ISSUE TITLE
Add telescope keymap binding to delete bookmark

### ISSUE THREAD

**Issue by niba** [LintaoAmons/bookmarks.nvim#23]
Right now, it takes too much time to delete multiple bookmarks. It would be good to have the possibility to configure a keymap that removes bookmarks from Telescope entries while browsing them.

**Comment by LintaoAmons** [comment]
Yeah~ May find some time to add it~ PR is also very welcome👻

**Comment by Kailian-Jacy** [comment]
As a super fan of telescope, I think the keymap of project telescope-file-browser (*https://github.com/nvim-telescope/telescope-file-browser.nvim*) is highly efficiency and suitable for our project:
- Display objects with list (just as we do)
- Delegate all actions (create, delete, move, rename etc) to telescope.actions with intuitive keybindings.
This largely simplify my workflow, I just bind one keymap as entry, e.g. `<leader>fm` to list all bookmarks, and operate on items selected, like with <A-d>/d for deletion.
So we don't need multiple steps for frequent operations (open command list -> select command -> list all book marks), only one step is needed: (open all bookmarks).

Personally I think this set of mapping is the best. Bookmarks are just like file system (list, goto, display, add/rename/delete).

**Comment by LintaoAmons** [comment]
It is available in the `refactor-remodel-and-sqlite` branch. You can try it(be careful of breaking change and data lose) or wait until it is merged to main.

**Comment by LintaoAmons** [comment]
merged and able to use
