### ISSUE TITLE
bug: config.treeview.bookmark_format not called due to typo in lua/bookmarks/tree/render/bookmark.lua

### ISSUE THREAD

**Issue by SiyuLiu0329** [LintaoAmons/bookmarks.nvim#29]
Hi, i noticed that my custom `bookmark_format` function is not being called. I found a typo in `lua/bookmarks/tree/render/bookmark.lua` causing this issue:
<img width="881" alt="Screenshot 2024-08-05 at 10 31 12 am" src="https://github.com/user-attachments/assets/4d981a72-5ffb-487e-acf5-e4ac69cca7df">

**Comment by LintaoAmons** [comment]
fixed~ thx
