### ISSUE TITLE
bookmark_format option doesn't work

### ISSUE THREAD

**Issue by karamanliev** [LintaoAmons/bookmarks.nvim#30]
Trying to change the `bookmark_format` key does nothing for me? Also the quit keys don't work for some reason.

```lua
        treeview = {
          bookmark_format = function(bookmark)
            return bookmark.name
          end,
          keymap = {
            quit = { 'q', '<ESC>' },
...
```

Results in:
![image](https://github.com/user-attachments/assets/1becfa98-c66c-4469-8c3d-f20bdfc0ae8a)

**Comment by LintaoAmons** [comment]
Please update the fix

Same issue and fixed: https://github.com/LintaoAmons/bookmarks.nvim/issues/29

**Comment by karamanliev** [comment]
Thanks for the fix! Unfortunately the quit keybind still does not work.

**Comment by LintaoAmons** [comment]
Ah, thx and fixed~
