### ISSUE TITLE
If the file has been modified but not save will throw the exception

### ISSUE THREAD

**Issue by shanlihou** [LintaoAmons/bookmarks.nvim#33]
E5108: Error executing lua: ...e/pack/packer/start/bookmarks.nvim/lua/bookmarks/api.lua:86: nvim_exec2(): Vim(edit):E37: 已修改但尚未保存 (可用 ! 强制执行)
stack traceback:
        [C]: in function 'nvim_exec2'
        ...e/pack/packer/start/bookmarks.nvim/lua/bookmarks/api.lua:86: in function 'goto_bookmark'
        ...start/bookmarks.nvim/lua/bookmarks/adapter/telescope.lua:7: in function 'callback'
        ...er/start/bookmarks.nvim/lua/bookmarks/adapter/picker.lua:103: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:293: in function <...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:292>

**Comment by LintaoAmons** [comment]
fixed by send notification to user
