### ISSUE TITLE
添加书签后，修改了文件，书签位置有问题

### ISSUE THREAD

**Issue by hyawara** [LintaoAmons/bookmarks.nvim#35]
步骤：

1. 在文件中添加书签，如 23 行
![image](https://github.com/user-attachments/assets/7042e660-0001-4a32-ad9d-788b565bbde0)

2. 修改文件，原来的 23 行变为 25 行， 此时书签位置是正确的
![image](https://github.com/user-attachments/assets/3386bd2e-7476-45ab-b506-52d89ab20e41)

3. 退出nvim, 重新打开文件，运行命令：BookmarksTree, 书签显示还在 23 行。
![image](https://github.com/user-attachments/assets/7ef74b55-bc9b-43a4-b7f4-be7dded9348f)

**Comment by LintaoAmons** [comment]
是的，因为在 toggle_mark 的时候，mark的位置已经被存下来了，同时 sign 和 line highlight 也出来了，
再继续编辑，sign是neovim的ext_mark, 会跟着变，但是 mark 的位置不会同时 update。

https://github.com/LintaoAmons/bookmarks.nvim/pull/31 这个 PR 在做补偿，校准

**Comment by hyawara** [comment]
好的，非常感谢，已star。

另外想问个问题，就是 BookmarksTree，打开之后，按下Enter 会跳转到对应的书签位置，这个有在考虑实现吗。

**Comment by LintaoAmons** [comment]
collapse = "o",
      
      果然，这个名字要改改

**Comment by hyawara** [comment]
> ```
>   collapse = "o",
>   
>   果然，这个名字要改改
> ```

我一直以为是收放文件夹的功能，从来没想过要在书签上 按下 "o"

**Comment by hyawara** [comment]
还有个问题，稍等我复现一下

**Comment by hyawara** [comment]
没复现出来，等下次回到公司后，我看看能不能截图出来。

我大概描述一下：就是当我使用 BookmarksGoto 命令的时候会出错，提示 format ：%-123 异常：具体的代码行数为：

![image](https://github.com/user-attachments/assets/0c2326a4-4518-47b6-a20b-903d7c988b28)

后面我复制的时候截图具体的报错内容。

**Comment by hyawara** [comment]
我先关闭当前这个问题。后面再讨论 %-123 错误，感谢你的回复。
