### ISSUE TITLE
Which plugin provides this scope matching indicator? 

### ISSUE THREAD

**Issue by unphased** [LintaoAmons/bookmarks.nvim#36]
<img width="80" alt="image" src="https://github.com/user-attachments/assets/a0b461ab-906a-4cda-bb00-e69b0ab623c8">

I'm referring to the cool purple curved arrow. 
Sorry for spamming your issues.

**Comment by unphased** [comment]
It looks like it may be https://github.com/shellRaining/hlchunk.nvim

**Comment by LintaoAmons** [comment]
https://github.com/LintaoAmons/CoolStuffes/blob/main/nvim/.config/nvim/lua/plugins/ui/hlchuck.lua


yes
