### ISSUE TITLE
Next/Prev mark in the active list (order by order id)

### ISSUE THREAD

**Issue by LintaoAmons** [LintaoAmons/bookmarks.nvim#48]
this will be helpful when spick a flow and also show other with your ordered locations.

**Comment by LintaoAmons** [comment]
@nfginola if you are interested in impl this feature as well? It's OK if you don't have time

**Comment by nfginola** [comment]
Hi, I'm interested and can do it when I find the time to. However I would do it in conjunction with adding the ability to re-order your bookmarks (change order ID) arbitrarily. Together, I think would be a powerful feature.

The use case I'm thinking is:
- Assume I use a list to bookmark contextual pieces of code for a problem I'm solving
- I create bookmark for each line of interest
- I want to re-order them arbitrarily so I can cycle through them in a meaningful order for me (for example, code logic that are littered around)

The question is, is it trivial to add bookmark re-ordering, or does the plugin consider them a purely internal thing ID not to be modified by the user?
I haven't read up on how order id is manipulated yet.

**Comment by LintaoAmons** [comment]
> Hi, I'm interested and can do it when I find the time to. However I would do it in conjunction with adding the ability to re-order your bookmarks (change order ID) arbitrarily within a BookmarkList.

Hi, this is already achieved by bookmarkTree.

User can mark any place arbitrarily then using `cut/paste` or `switch order` operations in bookmarkTree to reorder the bookmarks in the list.
