### ISSUE TITLE
Traverse bookmarks independent of bookmark insertion order

### ISSUE THREAD

**Issue by nfginola** [LintaoAmons/bookmarks.nvim#51]
Following #48

**Use case:**
- Assume a situation where we might be exploring some code base we are not familiar with containing littered logic
- We bookmark some places of interest first and write some description for it. At first we do not know the meaningful order we want to traverse them so these are bookmarked in random order.
- Afterwards, when we figure out the meaningful order after some reading of the code, we would like to keep all the information from the bookmark (description) and also have a way to traverse the bookmark in this new order, which isn't necessarily the in order id sequence (initial insert order).

(In other words, we don't want to make a new list with bookmarks in the correct order since we want to keep the description data from our 'exploration' bookmarks)

Instead of touching order ID (which appears to be insertion order in the current implementation), I propose that we add a separate **traversal list** for users to insert and remove.

**Example Actions by User:**
- User creates a traversal list L
- Add bookmarks by going to a bookmark in any BookmarkList X, Y, Z and calling some command.
- L now has { X.a, X.b, X.d, Y.f, Y.h, Z.b } where each entry is a bookmark (lowercase letter) from a list (capital letter)

The idea here is we want a **ListView**.

In this case, we would have to have a separate concept of 'active traverse list' as we would like to be able to browse our 'active' list to add to our 'traverse list'.

A solution would be to have a list referencing bookmarks from other lists (preserve all information), but then **only override** the order id to new monotonically increasing values based on when we insert each bookmark into the traversal list.

Thoughts?

**Comment by nfginola** [comment]
I completely didn't see but there is already some reordering work going on with the Tree using Service.switch_positions.
I haven't checked this feature out, is this ready for use?

It'd be great if you could do this in the normal bookmark viewer, unless the Tree is meant to replace the current viewer.

**Comment by LintaoAmons** [comment]
> Instead of touching order ID (which appears to be insertion order in the current implementation), I propose that we add a separate traversal list for users to insert and remove.

We can do it with order id (actually it is the original idea that it been added, and we have created datetime if we want to know the creation order)

**Comment by LintaoAmons** [comment]
>Use case:
> - Assume a situation where we might be exploring some code base we are not familiar with containing littered logic
> - We bookmark some places of interest first and write some description for it. At first we do not know the meaningful order we want to traverse them so these are bookmarked in random order.

BTW, I found your description is super good, this is exactly idea in my mind~ My poor English
