### ISSUE TITLE
Body of text

### ISSUE THREAD

**Issue by foersben** [LintaoAmons/bookmarks.nvim#9]
Dear LintaoAmons,
is it possible/will it be possible to add a body of text to each bookmark e.g. instead of just a title, which is visible in the line associated with the bookmark, will it also be possible to add a body of text explaining some details. 

This would be particularly useful, if I want to use the bookmarks to plan e.g. a latex document and split it into detailed topic-related parts (beyond sections/subsections and paragraphs).

Additionally, I would love to view the BookmarkList (or even different Bookmark lists in a tree-view) in a sidebar (left/right), is there already an option to do something like this?

Thanks for the plugin so far, already like it, just started using it within the discovered boundaries, and I am very happy.

**Comment by LintaoAmons** [comment]
Yes， description should be very helpful and I can imagine that we can have some sort of commands can peek the description.

And tree-like view is some I also want to have but right now limited by my knowledge can't think about how to achieve it. So can can see in the readme, I put it into goals of V2

**Comment by ttytm** [comment]
Great feature request @LintaoAmons what about adding a telescope integration it could achieve this I think.

**Comment by LintaoAmons** [comment]
It is available in the refactor-remodel-and-sqlite branch. You can try it(be careful of breaking change and data lose) or wait until it is merged to main.

**Comment by LintaoAmons** [comment]
new command to attach description to a bookmark
